# Generated by Django 6.0.2 on 2026-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#d1e7dd', 'Verde'), ('#f8d7da', 'Rojo'), ('#fff3cd', 'Amarillo'), ('#cff4fc', 'Azul'), ('#e2e3e5', 'Gris'), ('#f3e5f5', 'Morado')], default='#cff4fc', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='boards.tag'),
        ),
    ]
