# Generated by Django 6.0.2 on 2026-02-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
