# Generated by Django 6.0.2 on 2026-02-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_owner_memberships(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    BoardMembership = apps.get_model("boards", "BoardMembership")
    for board in Board.objects.all():
        BoardMembership.objects.get_or_create(
            board=board,
            user=board.owner,
            defaults={"role": "owner"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_userprofile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('board', 'user')},
            },
        ),
        migrations.RunPython(
            code=create_owner_memberships,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
