# Generated by Django 6.0.2 on 2026-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardinvite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boardinvite',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='boardinvite',
            unique_together={('board', 'username', 'email')},
        ),
    ]
