# Generated by Django 6.0.2 on 2026-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_task_assigned',
            field=models.BooleanField(default=True),
        ),
    ]
