# Generated by Codex on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0013_userprofile_notify_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_soon_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="overdue_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_task_due",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_task_status",
            field=models.BooleanField(default=True),
        ),
    ]
