# Generated by Codex on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0014_task_due_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_email_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_email_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
