# Generated by Django 6.0.2 on 2026-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_userprofile_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cookie_consent',
            field=models.CharField(blank=True, choices=[('all', 'Aceptar todas'), ('essential', 'Solo imprescindibles'), ('reject', 'Rechazar todas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cookie_consent_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
